export {
  activateFrontmatterStructureEdit,
  activateStructureEditAt,
  activateStructureEditTarget,
  activeStructureEditField,
  clearStructureEditTarget,
  createFencedStructureEditTarget,
  createStructureEditTargetAt,
  getActiveStructureEditTarget,
  hasStructureEditEffect,
  isCodeFenceStructureEditActive,
  isFencedStructureEditActive,
  isFootnoteLabelStructureEditActive,
  isFrontmatterStructureEditActive,
  setStructureEditTargetEffect,
  structureEditTargetContainsPos,
  type CodeFenceStructureEditTarget,
  type DisplayMathStructureEditTarget,
  type FencedStructureEditTarget,
  type FootnoteLabelStructureEditTarget,
  type FrontmatterStructureEditTarget,
  type StructureEditTarget,
} from "../state/cm-structure-edit";
