bib: test.bib
csl: test.csl
lua-filters: [abstract-section,theorem-environment,algorithm,blockref]
format:
  html:
    css: test.css
    html-math-method: katex
    toc: true
    template: template.html