export const templateSource = [
  "import {",
  "  assertEditorHealth,",
  "  openRegressionDocument,",
  "  withRuntimeIssueCapture,",
  '} from "../test-helpers.mjs";',
  "",
  'export const name = "__TEST_NAME__";',
  "",
  "export async function run(page) {",
  "  const { issues } = await withRuntimeIssueCapture(page, async () => {",
  "    await openRegressionDocument(page);",
  "",
  "    // Arrange:",
  "    //   Use page.evaluate(), locators, or debug globals to set up the document.",
  "    // Act:",
  "    //   Drive the browser exactly as the user would.",
  "    // Assert:",
  "    //   Return { pass: false, message } for behavioral failures.",
  "",
  "    await assertEditorHealth(page, name);",
  "  });",
  "",
  "  if (issues.length > 0) {",
  "    return {",
  "      pass: false,",
  '      message: issues.map((issue) => `[${issue.source}] ${issue.text}`).join(" | "),',
  "    };",
  "  }",
  "",
  "  return {",
  "    pass: true,",
  '    message: "replace this with the verified behavior",',
  "  };",
  "}",
  "",
].join("\n");
