export const themeFoundationTokens = [
  "--cf-bg",
  "--cf-bg-secondary",
  "--cf-fg",
  "--cf-muted",
  "--cf-border",
  "--cf-subtle",
  "--cf-hover",
  "--cf-active",
  "--cf-accent",
  "--cf-accent-fg",
  "--cf-bg-overlay",
  "--cf-border-overlay",
  "--cf-border-radius",
  "--cf-border-radius-lg",
  "--cf-spacing-xs",
  "--cf-spacing-sm",
  "--cf-spacing-md",
  "--cf-spacing-lg",
  "--cf-border-width",
  "--cf-border-width-accent",
  "--cf-transition",
] as const;

export const themeLayerTokens = [
  "--cf-layer-inline-chrome",
  "--cf-layer-preview-surface",
  "--cf-layer-block-picker",
] as const;

export const themeLayerTokenDefaults: Record<(typeof themeLayerTokens)[number], string> = {
  "--cf-layer-inline-chrome": "1",
  "--cf-layer-preview-surface": "1000",
  "--cf-layer-block-picker": "1010",
};

export const themeBlockTokens = [
  "--cf-block-header-accent",
  "--cf-block-header-border-width",
  "--cf-block-title-color",
  "--cf-block-title-weight",
  "--cf-block-title-display",
  "--cf-block-title-separator",
  "--cf-block-margin",
  "--cf-block-theorem-accent",
  "--cf-block-theorem-style",
  "--cf-block-lemma-accent",
  "--cf-block-lemma-style",
  "--cf-block-corollary-accent",
  "--cf-block-corollary-style",
  "--cf-block-proposition-accent",
  "--cf-block-proposition-style",
  "--cf-block-conjecture-accent",
  "--cf-block-conjecture-style",
  "--cf-block-definition-accent",
  "--cf-block-definition-style",
  "--cf-block-problem-accent",
  "--cf-block-problem-style",
  "--cf-block-example-accent",
  "--cf-block-example-style",
  "--cf-block-remark-accent",
  "--cf-block-remark-style",
  "--cf-block-proof-accent",
  "--cf-block-proof-style",
  "--cf-block-algorithm-accent",
  "--cf-block-algorithm-style",
  "--cf-block-figure-accent",
  "--cf-block-figure-style",
  "--cf-block-table-accent",
  "--cf-block-table-style",
  "--cf-block-nest-1",
  "--cf-block-nest-2",
  "--cf-block-nest-3",
  "--cf-block-nest-4",
  "--cf-proof-marker",
  "--cf-proof-marker-color",
  "--cf-proof-marker-size",
] as const;

export const themeTableTokens = [
  "--cf-blockquote-border",
  "--cf-blockquote-color",
  "--cf-table-border",
  "--cf-table-header-border",
  "--cf-table-cell-padding",
  "--cf-table-font-size",
  "--cf-table-line-height",
  "--cf-table-edit-outline",
  "--cf-mark-bg",
  "--cf-math-error-fg",
  "--cf-math-error-bg",
] as const;

export const themeTypographyTokens = [
  "--cf-ui-font",
  "--cf-content-font",
  "--cf-code-font",
  "--cf-base-font-size",
  "--cf-line-height",
  "--cf-content-max-width",
  "--cf-sidenote-width",
  "--cf-fence-guide-width",
  "--cf-ui-font-size-sm",
  "--cf-ui-font-size-base",
  "--cf-h1-size",
  "--cf-h1-weight",
  "--cf-h1-style",
  "--cf-h2-size",
  "--cf-h2-weight",
  "--cf-h2-style",
  "--cf-h3-size",
  "--cf-h3-weight",
  "--cf-h3-style",
  "--cf-h4-size",
  "--cf-h4-weight",
  "--cf-h4-style",
  "--cf-h5-size",
  "--cf-h5-weight",
  "--cf-h5-style",
  "--cf-h6-size",
  "--cf-h6-weight",
  "--cf-h6-style",
] as const;

export const themePreviewTokens = [
  "--cf-preview-surface-max-width",
  "--cf-preview-surface-max-height",
  "--cf-preview-surface-padding-block",
  "--cf-preview-surface-padding-inline",
  "--cf-preview-surface-font-size",
] as const;

export const themeTokenNames = [
  ...themeFoundationTokens,
  ...themeLayerTokens,
  ...themeBlockTokens,
  ...themeTableTokens,
  ...themeTypographyTokens,
  ...themePreviewTokens,
] as const;

export type ThemeTokenName = (typeof themeTokenNames)[number];
export type WritingThemeVariables = Partial<Record<ThemeTokenName, string>>;

export const themeSurfaceTokenMap = {
  appChrome: [
    "--cf-bg",
    "--cf-bg-secondary",
    "--cf-fg",
    "--cf-muted",
    "--cf-border",
    "--cf-hover",
    "--cf-active",
    "--cf-accent",
    "--cf-accent-fg",
    "--cf-ui-font",
    "--cf-ui-font-size-sm",
    "--cf-ui-font-size-base",
    "--cf-border-radius",
    "--cf-border-radius-lg",
    "--cf-spacing-xs",
    "--cf-spacing-sm",
    "--cf-spacing-md",
    "--cf-spacing-lg",
    "--cf-border-width",
    "--cf-border-width-accent",
    "--cf-transition",
    "--cf-layer-inline-chrome",
    "--cf-layer-preview-surface",
    "--cf-layer-block-picker",
  ],
  editorBody: [
    "--cf-bg",
    "--cf-fg",
    "--cf-content-font",
    "--cf-code-font",
    "--cf-base-font-size",
    "--cf-line-height",
    "--cf-content-max-width",
    "--cf-sidenote-width",
    "--cf-fence-guide-width",
  ],
  readMode: [
    "--cf-bg",
    "--cf-fg",
    "--cf-content-font",
    "--cf-code-font",
    "--cf-base-font-size",
    "--cf-line-height",
    "--cf-content-max-width",
  ],
  blockSurfaces: [
    "--cf-fg",
    "--cf-block-header-accent",
    "--cf-block-header-border-width",
    "--cf-block-title-color",
    "--cf-block-title-weight",
    "--cf-block-title-display",
    "--cf-block-title-separator",
    "--cf-block-margin",
    "--cf-block-theorem-accent",
    "--cf-block-lemma-accent",
    "--cf-block-corollary-accent",
    "--cf-block-proposition-accent",
    "--cf-block-conjecture-accent",
    "--cf-block-definition-accent",
    "--cf-block-problem-accent",
    "--cf-block-example-accent",
    "--cf-block-remark-accent",
    "--cf-block-proof-accent",
    "--cf-block-algorithm-accent",
    "--cf-block-figure-accent",
    "--cf-block-table-accent",
    "--cf-block-nest-1",
    "--cf-block-nest-2",
    "--cf-block-nest-3",
    "--cf-block-nest-4",
    "--cf-proof-marker",
    "--cf-proof-marker-color",
    "--cf-proof-marker-size",
    "--cf-layer-inline-chrome",
  ],
  tables: [
    "--cf-border",
    "--cf-table-border",
    "--cf-table-header-border",
    "--cf-table-cell-padding",
    "--cf-table-font-size",
    "--cf-table-line-height",
    "--cf-table-edit-outline",
    "--cf-code-font",
  ],
  tooltipAndHover: [
    "--cf-bg-overlay",
    "--cf-border-overlay",
    "--cf-fg",
    "--cf-muted",
    "--cf-border",
    "--cf-preview-surface-max-width",
    "--cf-preview-surface-max-height",
    "--cf-preview-surface-padding-block",
    "--cf-preview-surface-padding-inline",
    "--cf-preview-surface-font-size",
    "--cf-layer-preview-surface",
  ],
} as const satisfies Record<string, readonly ThemeTokenName[]>;
