import {
  defaultCodeFontStack,
  defaultContentFontStack,
  defaultUIFontStack,
} from "./editor/editor-constants";

export const themeFoundationTokens = [
  "--cf-bg",
  "--cf-bg-secondary",
  "--cf-fg",
  "--cf-muted",
  "--cf-border",
  "--cf-subtle",
  "--cf-hover",
  "--cf-active",
  "--cf-accent",
  "--cf-accent-fg",
  "--cf-bg-overlay",
  "--cf-border-overlay",
  "--cf-separator",
] as const;

export const themeBlockTokens = [
  "--cf-block-title-color",
  "--cf-block-title-weight",
  "--cf-block-title-display",
  "--cf-block-title-separator",
  "--cf-block-margin",
  "--cf-block-theorem-style",
  "--cf-block-lemma-style",
  "--cf-block-corollary-style",
  "--cf-block-proposition-style",
  "--cf-block-conjecture-style",
  "--cf-block-definition-style",
  "--cf-block-problem-style",
  "--cf-block-example-style",
  "--cf-block-remark-style",
  "--cf-block-proof-style",
  "--cf-proof-marker",
  "--cf-proof-marker-color",
  "--cf-proof-marker-size",
] as const;

export const themeTableTokens = [
  "--cf-blockquote-border",
  "--cf-blockquote-color",
  "--cf-table-border",
  "--cf-table-header-border",
  "--cf-table-cell-padding",
  "--cf-mark-bg",
  "--cf-math-error-fg",
  "--cf-math-error-bg",
] as const;

export const themeTypographyTokens = [
  "--cf-ui-font",
  "--cf-content-font",
  "--cf-code-font",
  "--cf-base-font-size",
  "--cf-line-height",
  "--cf-content-max-width",
  "--cf-h1-size",
  "--cf-h1-weight",
  "--cf-h1-style",
  "--cf-h2-size",
  "--cf-h2-weight",
  "--cf-h2-style",
  "--cf-h3-size",
  "--cf-h3-weight",
  "--cf-h3-style",
  "--cf-h4-size",
  "--cf-h4-weight",
  "--cf-h4-style",
  "--cf-h5-size",
  "--cf-h5-weight",
  "--cf-h5-style",
  "--cf-h6-size",
  "--cf-h6-weight",
  "--cf-h6-style",
] as const;

export const themeTokenNames = [
  ...themeFoundationTokens,
  ...themeBlockTokens,
  ...themeTableTokens,
  ...themeTypographyTokens,
] as const;

export type ThemeTokenName = (typeof themeTokenNames)[number];
export type WritingThemeVariables = Partial<Record<ThemeTokenName, string>>;

export const themeSurfaceTokenMap = {
  appChrome: [
    "--cf-bg",
    "--cf-bg-secondary",
    "--cf-fg",
    "--cf-muted",
    "--cf-border",
    "--cf-hover",
    "--cf-active",
    "--cf-accent",
    "--cf-accent-fg",
    "--cf-ui-font",
  ],
  editorBody: [
    "--cf-bg",
    "--cf-fg",
    "--cf-content-font",
    "--cf-code-font",
    "--cf-base-font-size",
    "--cf-line-height",
    "--cf-content-max-width",
  ],
  readMode: [
    "--cf-bg",
    "--cf-fg",
    "--cf-content-font",
    "--cf-code-font",
    "--cf-base-font-size",
    "--cf-line-height",
    "--cf-content-max-width",
  ],
  blockSurfaces: [
    "--cf-fg",
    "--cf-block-title-color",
    "--cf-block-title-weight",
    "--cf-block-title-display",
    "--cf-block-title-separator",
    "--cf-block-margin",
    "--cf-proof-marker",
    "--cf-proof-marker-color",
    "--cf-proof-marker-size",
  ],
  tables: [
    "--cf-border",
    "--cf-table-border",
    "--cf-table-header-border",
    "--cf-table-cell-padding",
    "--cf-code-font",
  ],
  tooltipAndHover: [
    "--cf-bg-overlay",
    "--cf-border-overlay",
    "--cf-fg",
    "--cf-muted",
    "--cf-border",
  ],
  export: [...themeTokenNames],
} as const satisfies Record<string, readonly ThemeTokenName[]>;

export const exportThemeTokenDefaults: Record<ThemeTokenName, string> = {
  "--cf-bg": "#ffffff",
  "--cf-bg-secondary": "#ffffff",
  "--cf-fg": "#09090b",
  "--cf-muted": "#71717a",
  "--cf-border": "#e4e4e7",
  "--cf-subtle": "rgba(0, 0, 0, 0.02)",
  "--cf-hover": "rgba(0, 0, 0, 0.04)",
  "--cf-active": "rgba(0, 0, 0, 0.06)",
  "--cf-accent": "#18181b",
  "--cf-accent-fg": "#ffffff",
  "--cf-bg-overlay": "rgba(255, 255, 255, 0.82)",
  "--cf-border-overlay": "rgba(228, 228, 231, 0.6)",
  "--cf-separator": "rgba(113, 113, 122, 0.6)",
  "--cf-block-title-color": "var(--cf-fg)",
  "--cf-block-title-weight": "700",
  "--cf-block-title-display": "inline",
  "--cf-block-title-separator": '".\\2002\\2002"',
  "--cf-block-margin": "0.6em 0",
  "--cf-block-theorem-style": "italic",
  "--cf-block-lemma-style": "italic",
  "--cf-block-corollary-style": "italic",
  "--cf-block-proposition-style": "italic",
  "--cf-block-conjecture-style": "italic",
  "--cf-block-definition-style": "normal",
  "--cf-block-problem-style": "normal",
  "--cf-block-example-style": "normal",
  "--cf-block-remark-style": "normal",
  "--cf-block-proof-style": "normal",
  "--cf-proof-marker": '"\\220E"',
  "--cf-proof-marker-color": "var(--cf-fg)",
  "--cf-proof-marker-size": "1.2em",
  "--cf-blockquote-border": "var(--cf-border)",
  "--cf-blockquote-color": "var(--cf-fg)",
  "--cf-table-border": "var(--cf-border)",
  "--cf-table-header-border": "var(--cf-border)",
  "--cf-table-cell-padding": "0.5em 0.75em",
  "--cf-mark-bg": "rgba(255, 255, 0, 0.2)",
  "--cf-math-error-fg": "#c00",
  "--cf-math-error-bg": "rgba(255, 0, 0, 0.05)",
  "--cf-ui-font": defaultUIFontStack,
  "--cf-content-font": defaultContentFontStack,
  "--cf-code-font": defaultCodeFontStack,
  "--cf-base-font-size": "16px",
  "--cf-line-height": "1.5",
  "--cf-content-max-width": "800px",
  "--cf-h1-size": "1.15em",
  "--cf-h1-weight": "700",
  "--cf-h1-style": "normal",
  "--cf-h2-size": "1.15em",
  "--cf-h2-weight": "400",
  "--cf-h2-style": "italic",
  "--cf-h3-size": "1.1em",
  "--cf-h3-weight": "600",
  "--cf-h3-style": "italic",
  "--cf-h4-size": "1.05em",
  "--cf-h4-weight": "600",
  "--cf-h4-style": "normal",
  "--cf-h5-size": "1em",
  "--cf-h5-weight": "600",
  "--cf-h5-style": "normal",
  "--cf-h6-size": "0.95em",
  "--cf-h6-weight": "600",
  "--cf-h6-style": "normal",
};
